name: Testing
run-name: ${{ github.actor }} is testing the backend
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # - name: locate package.json
      #   run: cd trainspy
      - name: Install dependencies
        run: npm install jest
      - run: npm run test
